// <auto-generated />
namespace CardiologicalResearch.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_12));
        
        string IMigrationMetadata.Id
        {
            get { return "201711042215590_12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
