// <auto-generated />
namespace CardiologicalResearch.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _02112017 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_02112017));
        
        string IMigrationMetadata.Id
        {
            get { return "201711021138354_02112017"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
